### ISSUE TITLE
two independent watercourses system

### ISSUE THREAD

**Issue by kavkapet** [storm-fsv-cvut/smoderp2d#338] opened 2024-02-21 11:38 UTC
computation faild, if are two independent (nonconnected) streams in the computation domain.

**Comment by pesekon2** [comment] 2024-02-24 20:01
Judging from the screenshots you have attached and tests I have made, the error was actually raised by the stream having zero slope (exactly what it says in your error log), not by having two streams.

**Comment by pesekon2** [comment] 2024-03-11 11:55
> Judging from the screenshots you have attached and tests I have made, the error was actually raised by the stream having zero slope (exactly what it says in your error log), not by having two streams.

Closing the issue as it was probably caused by this.

**Closed by pesekon2** 2024-03-11 11:55 UTC
Labels: bug
