### ISSUE TITLE
arcgis provider testing data error: copyraster_management error (see comment)

### ISSUE THREAD

**Issue by jerabekjak** [storm-fsv-cvut/smoderp2d#46] opened 2019-09-03 12:46 UTC
two version of arcmap gives an error while running the testing data with the arcgis toolbox. 
error message in arcmap 10.6
![image](https://user-images.githubusercontent.com/10115010/64174009-d5beb580-ce58-11e9-8309-e76a5833318c.png)
error message in arcmap 10.5
![image](https://user-images.githubusercontent.com/10115010/64174166-fdae1900-ce58-11e9-9739-82bf4fbbac06.png)

**Comment by jerabekjak** [comment] 2019-09-03 14:43
the error is raised only with the testing data. 
nesting data needs to be checked.

**Comment by landam** [comment] 2019-09-05 10:19
@jerabekjak I am not able to reproduce this issue with ArcGIS Pro. I will try later ArcGIS 10 and let you know.

**Comment by landam** [comment] 2019-09-30 14:33
OK, I am getting the same error in ArcGIS Pro

```
Traceback (most recent call last):
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\start-smoderp2d.py", line 13, in <module>
    sys.exit(runner.run())
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\__init__.py", line 66, in run
    self._provider.load()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\base\__init__.py", line 144, in load
    data = self._load_dpre()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\arcgis\__init__.py", line 55, in _load_dpre
    return prep.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\base\data_preparation.py", line 53, in run
    dem_copy, dem_mask = self._set_mask()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\arcgis\data_preparation.py", line 122, in _set_mask
    self._input_params['elevation'], dem_copy
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 14294, in CopyRaster
    raise e
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 14291, in CopyRaster
    retval = convertArcObjectToPythonObject(gp.CopyRaster_management(*gp_fixargs((in_raster, out_rasterdataset, config_keyword, background_value, nodata_value, onebit_to_eightbit, colormap_to_RGB, pixel_type, scale_pixel_value, RGB_to_Colormap, format, transform), True)))
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 496, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError:  ERROR 999999: Something unexpected caused the tool to fail. Please refer to the error help for potential solutions, or contact Esri Technical Support http://esriurl.com/support.
Failed to copy raster dataset
Failed to execute (CopyRaster).
 Failed to execute (SMODERP2D2).
```

**Comment by landam** [comment] 2019-09-30 14:35
> 
> 
> the error is raised only with the testing data.
> testing data needs to be checked.

@jerabekjak No idea what is wrong. I checked input and output parameters of copyraster function. Input raster exists and it's possible to load it into ArcGIS. Output directory exists, so output file can be created. Strange.

**Comment by landam** [comment] 2019-09-30 15:34
I tried to read input data also by `arcpy.describe` method, it works. Input data can be read by ArcGIS.

**Comment by landam** [comment] 2019-09-30 15:55
It seems that CopyRaster works when output is set to GDB GRID. Strangely other arcpy methods happily stores output to GRID format with no problem.

**Comment by jerabekjak** [comment] 2019-10-08 17:10
dem_desc.noDataValue at [1] returns None. 
the NoDataValue is most likely lost at [2] where `self._input_params['elevation']` still has the nodatavelue but `dem_copy` has not.


[1] https://github.com/storm-fsv-cvut/smoderp2d/blob/8420b765ab887fedfdb059c03964e8c2c0a5e84c/smoderp2d/providers/arcgis/data_preparation.py#L308
[2] https://github.com/storm-fsv-cvut/smoderp2d/blob/8420b765ab887fedfdb059c03964e8c2c0a5e84c/smoderp2d/providers/arcgis/data_preparation.py#L103-L105

**Comment by jerabekjak** [comment] 2019-10-10 14:06
commit 6f727bd73cb7dcc6a60da1ba47e483cf88500ae7 only solves problem reported in [1]
output rasters does not have no data value set.
[1] https://github.com/storm-fsv-cvut/smoderp2d/issues/46#issuecomment-539611871

**Closed** 2019-11-05 16:20 UTC
Labels: bug, data preparation
