### ISSUE TITLE
Fail during creating DEM-derived layers..

### ISSUE THREAD

**Issue by TomasLib** [storm-fsv-cvut/smoderp2d#417] opened 2024-08-31 23:59 UTC
The process fails after 10s, whem its starts creating DEM layers. It happened with test data and also with my data.

Here is log file:
2024-09-01 01:55:59,443 - SMODERP2D - DEBUG - File logger set to D:/QGIS/vystupy\smoderp2d.log - [__init__:350]
2024-09-01 01:56:01,720 - SMODERP2D - INFO - -------------------------------------------------------------------------------- - [data_preparation:513]
2024-09-01 01:56:01,720 - SMODERP2D - INFO - DATA PREPARATION - [data_preparation:514]
2024-09-01 01:56:01,734 - SMODERP2D - INFO - Creating output directories <D:/QGIS/vystupy> - [data_preparation:697]
2024-09-01 01:56:01,735 - SMODERP2D - DEBUG - Creating temp directory <D:/QGIS/vystupy\temp> - [data_preparation:704]
2024-09-01 01:56:01,736 - SMODERP2D - DEBUG - Creating control directory <D:/QGIS/vystupy\control> - [data_preparation:704]
2024-09-01 01:56:01,736 - SMODERP2D - INFO - Creating intersect of input datasets ... - [data_preparation:523]
2024-09-01 01:56:10,910 - SMODERP2D - PROGRESS - 4 - [logger:46]
2024-09-01 01:56:10,912 - SMODERP2D - INFO - Creating DEM-derived layers... - [data_preparation:543]

**Comment by pesekon2** [comment] 2024-09-03 13:37
@TomasLib: Weird, it works for me. Does it generate some error message (maybe in another tab, if you are using it in QGIS)? Which test data do you use (Nučice/rain simulator)?

**Comment by TomasLib** [comment] 2024-09-03 14:02
Yes, I used Nučice in QGIS in latest version 3.34.10-Prizren. It only creates this popup message:
![image](https://github.com/user-attachments/assets/be3a8a8e-1bdb-4e44-8be0-0f6da3d59c72)

**Comment by pesekon2** [comment] 2024-09-03 14:16
I got 3.34.4 so I guess the issue is not in QGIS. Do you have some other plugins installed? Could you try to turn them off (we encountered one plugin that was locking correct error messages parsing in the past)? Then after failure, you should see something like `Python errors` or maybe it will be in `Python warnings` in the bottom bar (in my example, I see Plugins, Messages, General, Python warning, SMODERP2D).

![image](https://github.com/user-attachments/assets/aeca9cc6-e9bc-4379-8317-da16677d0bfd)

**Comment by TomasLib** [comment] 2024-09-03 17:30
![image](https://github.com/user-attachments/assets/0731691e-6cbd-4faf-9002-271c6981574a)

**Comment by TomasLib** [comment] 2024-09-03 17:31
2024-09-03T19:28:47     WARNING    An error has occurred while executing Python code:
             
             
             xml.etree.ElementTree.ParseError: no element found: line 1, column 0
             
             
             Traceback (most recent call last):
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp_2D_dockwidget.py", line 90, in run
              self.runner.run()
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\base.py", line 71, in run
              self._provider.load()
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\base\__init__.py", line 355, in load
              data = self._load_dpre()
              ^^^^^^^^^^^^^^^^^
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\grass\__init__.py", line 138, in _load_dpre
              return prep.run()
              ^^^^^^^^^^
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\base\data_preparation.py", line 544, in run
              dem_filled, dem_flowdir, dem_flowacc, dem_slope, dem_aspect = self._create_DEM_derivatives(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\grass\data_preparation.py", line 165, in _create_DEM_derivatives
              self._run_grass_module(
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\grass\data_preparation.py", line 719, in _run_grass_module
              m = Module(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\grass\grass84\etc\python\grass\pygrass\modules\interface\module.py", line 563, in __init__
              tree = fromstring(self.xml)
              ^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\Python312\Lib\xml\etree\ElementTree.py", line 1336, in XML
              return parser.close()
              ^^^^^^^^^^^^^^
             xml.etree.ElementTree.ParseError: no element found: line 1, column 0
             
             
             
             
             Python version: 3.12.5 (main, Aug 8 2024, 11:21:54) [MSC v.1938 64 bit (AMD64)]
             
             
             QGIS version: 3.34.10-Prizren Prizren, 113de9e1
             
             
             Python Path:
             
             C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_pluginC:/OSGeo4W/apps/qgis-ltr/./pythonC:/Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonC:/Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/pluginsC:/OSGeo4W/apps/qgis-ltr/./python/pluginsC:\OSGeo4W\apps\grass\grass84\etc\pythonC:\Users\t.libosvar\DocumentsC:\OSGeo4W\bin\python312.zipC:\OSGeo4W\apps\Python312\DLLsC:\OSGeo4W\apps\Python312\LibC:\OSGeo4W\binC:\OSGeo4W\apps\Python312C:\OSGeo4W\apps\Python312\Lib\site-packagesC:\OSGeo4W\apps\Python312\Lib\site-packages\win32C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\libC:\OSGeo4W\apps\Python312\Lib\site-packages\PythonwinC:/Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonD:/OGIS/Smoderp-nuciceC:\OSGeo4W\apps\grass\grass84\etc\python

**Comment by TomasLib** [comment] 2024-09-03 17:32
2024-09-03T19:28:47     WARNING    warning:C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\base.py:113: ResourceWarning: unclosed file 
              Logger.handlers = []
             
             traceback: File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp_2D_dockwidget.py", line 108, in finished
              self.runner.finish()
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\grass.py", line 73, in finish
              super().finish()
              File "C:\Users/t.libosvar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\base.py", line 113, in finish
              Logger.handlers = []

**Comment by pesekon2** [comment] 2024-09-03 21:40
Thanks, now it is more visible when exactly the issue happens. Is it possible that you are missing the `r.hydrodem` addon in GRASS GIS? Could you try opening GRASS GIS, running `g.extension r.hydrodem`, and then running the QGIS plugin again?

Also, please paste here the output from the `g.extension r.hydrodem` command.

**Comment by TomasLib** [comment] 2024-09-04 10:10
Yes, hydrodem was missing

**output from the g.extension r.hydrodem**
(Wed Sep  4 12:09:40 2024)                                                      
r.hydrodem input=dem@PERMANENT output=hydrodem mod=4 size=4                     
WARNING: Module built against version e49c044e62 but trying to use version 8.4.0. In case of errors you need to rebuild the module against GRASS GIS version 8.4.0 (2024).
Load elevation map
ERROR: No non-NULL cells loaded from input map
(Wed Sep  4 12:09:40 2024) Command ended with non-zero return code 1 (0 sec)

**Comment by TomasLib** [comment] 2024-09-04 10:11
2024-09-04T12:08:28     WARNING    An error has occurred while executing Python code:
             
             
             xml.etree.ElementTree.ParseError: no element found: line 1, column 0
             
             
             Traceback (most recent call last):
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp_2D_dockwidget.py", line 90, in run
              self.runner.run()
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\base.py", line 71, in run
              self._provider.load()
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\base\__init__.py", line 355, in load
              data = self._load_dpre()
              ^^^^^^^^^^^^^^^^^
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\grass\__init__.py", line 138, in _load_dpre
              return prep.run()
              ^^^^^^^^^^
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\base\data_preparation.py", line 544, in run
              dem_filled, dem_flowdir, dem_flowacc, dem_slope, dem_aspect = self._create_DEM_derivatives(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\grass\data_preparation.py", line 165, in _create_DEM_derivatives
              self._run_grass_module(
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\providers\grass\data_preparation.py", line 719, in _run_grass_module
              m = Module(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\grass\grass84\etc\python\grass\pygrass\modules\interface\module.py", line 563, in __init__
              tree = fromstring(self.xml)
              ^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\Python312\Lib\xml\etree\ElementTree.py", line 1336, in XML
              return parser.close()
              ^^^^^^^^^^^^^^
             xml.etree.ElementTree.ParseError: no element found: line 1, column 0
             
             
             
             
             Python version: 3.12.5 (main, Aug 8 2024, 11:21:54) [MSC v.1938 64 bit (AMD64)]
             
             
             QGIS version: 3.34.10-Prizren Prizren, 113de9e1
             
             
             Python Path:
             
             C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_pluginC:/OSGeo4W/apps/qgis-ltr/./pythonC:/Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonC:/Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/pluginsC:/OSGeo4W/apps/qgis-ltr/./python/pluginsC:\OSGeo4W\apps\grass\grass84\etc\pythonC:\Users\Tom\OneDrive\DokumentyC:\OSGeo4W\bin\python312.zipC:\OSGeo4W\apps\Python312\DLLsC:\OSGeo4W\apps\Python312\LibC:\OSGeo4W\binC:\OSGeo4W\apps\Python312C:\OSGeo4W\apps\Python312\Lib\site-packagesC:\OSGeo4W\apps\Python312\Lib\site-packages\win32C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\libC:\OSGeo4W\apps\Python312\Lib\site-packages\PythonwinC:/Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonD:/QGISC:\OSGeo4W\apps\grass\grass84\etc\python

**Comment by TomasLib** [comment] 2024-09-04 10:11
2024-09-04T12:08:28     WARNING    warning:C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\base.py:113: ResourceWarning: unclosed file 
              Logger.handlers = []
             
             traceback: File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp_2D_dockwidget.py", line 108, in finished
              self.runner.finish()
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\grass.py", line 73, in finish
              super().finish()
              File "C:\Users/Tom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\base.py", line 113, in finish
              Logger.handlers = []

**Comment by TomasLib** [comment] 2024-09-05 08:46
I have reinstall QGIS, now the computating of smoderp  seems that its working.

**Comment by pesekon2** [comment] 2024-09-05 12:29
For sure not so long on the test data, I have the test in the standard setting (I usually used right click and then choose "load the test constellation" or something like that) finished in less than a minute. There must be some issue somewhere in the code.

**Comment by TomasLib** [comment] 2024-09-15 15:23
I tried to install smoderp from zip nad this shows:


Nemohu načíst zásuvný modul 'smoderp2d-master/bin/qgis/smoderp2d-plugin' 

ModuleNotFoundError: No module named 'smoderp2d-master/bin/qgis/smoderp2d-plugin' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'smoderp2d-master/bin/qgis/smoderp2d-plugin'


Verze Pythonu: 3.12.6 (main, Sep  7 2024, 18:59:42) [MSC v.1938 64 bit (AMD64)] 
QGIS verze: 3.34.11-Prizren Prizren, 2904bcec 

Python cesta:
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass84\etc\python
C:\Users\tomik\OneDrive\Dokumenty
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.

**Comment by TomasLib** [comment] 2024-09-15 15:35
And when I install smoderp from "plugin server" and run the test data, this shows:

Během vykonávání Python kódu se objevila chyba: 

KeyError: 'GISRC' 
Traceback (most recent call last):
  File "C:\Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp_2D_dockwidget.py", line 109, in finished
    self.runner.finish()
  File "C:\Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin\smoderp2d\runners\grass.py", line 71, in finish
    self._grass_session.finish()
  File "C:\OSGeo4W\apps\grass\grass84\etc\python\grass\script\setup.py", line 437, in finish
    finish(start_time=self._start_time)
  File "C:\OSGeo4W\apps\grass\grass84\etc\python\grass\script\setup.py", line 527, in finish
    gutils.try_remove(os.environ["GISRC"])
                      ~~~~~~~~~~^^^^^^^^^
  File "", line 714, in __getitem__
KeyError: 'GISRC'


Verze Pythonu: 3.12.6 (main, Sep  7 2024, 18:59:42) [MSC v.1938 64 bit (AMD64)] 
QGIS verze: 3.34.11-Prizren Prizren, 2904bcec 

Python cesta:
C:\Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\smoderp2d_plugin
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass84\etc\python
C:\Users\tomik\OneDrive\Dokumenty
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/tomik/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
D:/QGIS/nucice
C:\OSGeo4W\apps\grass\grass84\etc\python

**Comment by TomasLib** [comment] 2024-09-15 15:46
New version of QGIS, new try of test data:

2024-09-15T17:44:12     INFO    Importing input data using GRASS GIS (C:\Users\tomik\AppData\Local\Temp\grassdata\578abe456304258c4bbec508c5d54a23\PERMANENT)...
2024-09-15T17:44:18     INFO    Input data successully imported
2024-09-15T17:44:18     INFO    File logger set to D:/QGIS/vystu2\smoderp2d.log
2024-09-15T17:44:19     INFO    --------------------------------------------------------------------------------
2024-09-15T17:44:19     INFO    DATA PREPARATION
2024-09-15T17:44:19     INFO    Creating output directories 
2024-09-15T17:44:19     INFO    Creating temp directory 
2024-09-15T17:44:19     INFO    Creating control directory 
2024-09-15T17:44:19     INFO    Creating intersect of input datasets ...
2024-09-15T17:44:27     INFO    Creating DEM-derived layers...
2024-09-15T17:44:29     INFO    Clipping layers to AoI outline...
2024-09-15T17:44:34     INFO     2 record points outside of the area of interest (FID: 5,6)
2024-09-15T17:44:34     INFO    Preparing points for hydrographs...
2024-09-15T17:44:34     INFO    Preparing soil and vegetation properties...
2024-09-15T17:44:46     INFO    Computing critical level...
2024-09-15T17:44:46     INFO    Raster ASCII output file saved
2024-09-15T17:44:46     INFO     Array stats: min=-9999.000 max=5.471 mean=-4433.061
2024-09-15T17:44:47     CRITICAL    Unexpected error: could not convert string to float: '
2024-09-15T17:44:47     CRITICAL    Invalid input for data preparation: Unexpected error: could not convert string to float: '
2024-09-15T17:44:47     CRITICAL    Unexpected error: could not convert string to float: '

**Comment by TomasLib** [comment] 2024-09-16 12:27
Its finally working!! Clean new instalation of Win 11, new QGIS 3.34.11. And I had to manually install addons in Grass, hydrodem, folw... as many, as I thought htat are connct to hydromodeling.

**Comment by pesekon2** [comment] 2024-09-17 18:13
@TomasLib: Great message, thanks! Sorry for the limited communication from my side in the last days/weeks, I was on travels. Thank you for writing the versions and everything so we have it noted down if it will be the case also for somebody else. Closing the issue as solved and good luck with the following works.

**Closed by pesekon2** 2024-09-17 18:13 UTC
Labels: bug
