### ISSUE TITLE
Watercourse calculation routine

### ISSUE THREAD

**Issue by kubatjanf** [storm-fsv-cvut/smoderp2d#206] opened 2023-08-14 15:37 UTC
In ArcGIS PRO If there are watercourses in the computation area, the computation time is significantly increased

**Comment by pesekon2** [comment] 2023-11-17 00:30
@kubatjanf: I believe that computations with streams were actually never working properly until about a month ago (15cd81b). Sorry for the late answer, but could you try it again with the current master? It is very possible that the issue is solved by now and was caused by erroneous stream handling.

**Comment by pesekon2** [comment] 2024-03-11 11:13
As I believe this is not an issue and it was reported before it was even fully working, I am closing the issue. Feel free to reopen it if you find it still valid.

**Closed by pesekon2** 2024-03-11 11:13 UTC
